- name: Configure ansible VM
  hosts: all
  become: true
  remote_user: ansible

  tasks:
    - name: Update system
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Install base packages
      ansible.builtin.apt:
        name:
          - curl
          - git
          - htop
          - python3
          - python3-pip
        state: present
