plugin: gcp_compute
projects:
  - cka-lfs-458
auth_kind: serviceaccount
# Key supplied by TF from BWS
# Path relative to ansible/, where ansible.cfg lives.
service_account_file: .gcp-sa-key.json

filters:
  labels.environment = "cka-lfs458"
  # labels.k8s_role = "control-plane,worker-node"

compose:
  node_name: name
  node_ip_internal: networkInterfaces[0].networkIP
  node_ip_public: networkInterfaces[0].accessConfigs[0].natIP
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP

keyed_groups:
  - key: labels.k8s_role
    prefix: ''

hostnames:
  - name

